### ISSUE TITLE
关于示例的User

### ISSUE THREAD

**Issue by pengjugame** [liangwei0101/egg-demo#1]
首先对作者表示非常非常的感谢，终于找到一个TS的框架能在上面做东西了（之前弄ts框架浪费好长好长时间），仔细看了下代码，有一个设计没有太明白，但在主页上没有找到作者的联系方式，只能在这里提问。

下面这段代码为什么要这样设计，会有什么好处呢？如果我要对它进行扩展字段，我应该怎么写才算是合理了。谢谢了。

并且希望能看到大佬的邮箱，可以向您交流学习。

```
/**
  * 用户字段接口
*/
export interface IUser {

  userNo: number;

  userName: string;
}

/**
  * 用户Document（实例方法在这写）
*/
export interface IUserDocument extends IUser, Document {

  /**
  * 实例方法接口（名称需要和Schema的方法名一样）
  */
 userInstanceTestMethods: () => IUser;
}

/**
  * 静态方法接口
*/
export interface IUserModel extends Model<IUserDocument> {

  /**
   * 静态方法
   */
  userStaticTestMethods: () => IUser;
}

export const UserModel = model<IUserDocument, IUserModel>('User', UserSchema);
```

**Comment by liangwei0101** [comment]
这个，我也琢磨了很久。这样写的话，你在egg的任何一个ts文件，都能使用 UserModel。
1. new UserModel() 出的对象都是继承于IUser。所以变量会有提示。
2. UserModel对象能只能点出静态方法。
3. UserModel能代替ctx.model.User，并且返回的变量是属于IUserDocument的。能够点出属性和实例方法。
