### ISSUE TITLE
yarn tsc 编译失败：app/extend/application.ts:7:15 - error TS2784: 'get' and 'set' accessors cannot declare 'this' parameters.

### ISSUE THREAD

**Issue by feliming** [liangwei0101/egg-demo#10]
$ yarn tsc
yarn run v1.22.4
$ ets && tsc -p tsconfig.json
[egg-ts-helper] create typings/app/extend/application.d.ts (4ms)
[egg-ts-helper] create typings/app/controller/index.d.ts (1ms)
[egg-ts-helper] create typings/app/model/index.d.ts (1ms)
[egg-ts-helper] create typings/config/index.d.ts (15ms)
[egg-ts-helper] create typings/config/plugin.d.ts (1ms)
[egg-ts-helper] create typings/app/service/index.d.ts (1ms)
[egg-ts-helper] create typings/app/index.d.ts (1ms)
app/extend/application.ts:7:15 - error TS2784: 'get' and 'set' accessors cannot declare 'this' parameters.

7   get graphql(this: Application): GraphQL {
                ~~~~~~~~~~~~~~~~~


Found 1 error.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by liangwei0101** [comment]
你好，由于 typescript的 V3.9版本的变动：“In older versions of TypeScript, get and set accessors in classes were emitted in a way that made them enumerable; however, this wasn't compliant with the ECMAScript specification which states that they must be non-enumerable. As a result, TypeScript code that targeted ES5 and ES2015 could differ in behavior.”导致的。

解决办法：将版本锁定在V3.7.2 即可。

代码已经上传，重新 pull 并且 install 。

谢谢你的关注

**Comment by liangwei0101** [comment]
> $ yarn tsc
> yarn run v1.22.4
> $ ets && tsc -p tsconfig.json
> [egg-ts-helper] create typings/app/extend/application.d.ts (4ms)
> [egg-ts-helper] create typings/app/controller/index.d.ts (1ms)
> [egg-ts-helper] create typings/app/model/index.d.ts (1ms)
> [egg-ts-helper] create typings/config/index.d.ts (15ms)
> [egg-ts-helper] create typings/config/plugin.d.ts (1ms)
> [egg-ts-helper] create typings/app/service/index.d.ts (1ms)
> [egg-ts-helper] create typings/app/index.d.ts (1ms)
> app/extend/application.ts:7:15 - error TS2784: 'get' and 'set' accessors cannot declare 'this' parameters.
> 
> 7 get graphql(this: Application): GraphQL {
> ~~~~~~~~~~~~~~~~~
> 
> Found 1 error.
> 
> error Command failed with exit code 2.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

你好，由于 typescript的 V3.9版本的变动：“In older versions of TypeScript, get and set accessors in classes were emitted in a way that made them enumerable; however, this wasn't compliant with the ECMAScript specification which states that they must be non-enumerable. As a result, TypeScript code that targeted ES5 and ES2015 could differ in behavior.”导致的。

解决办法：将版本锁定在V3.7.2 即可。

代码已经上传，重新 pull 并且 install 。

谢谢你的关注
