### ISSUE TITLE
如果是Schema.Types.ObjectId类型的定义下面的接口类型对应的是什么

### ISSUE THREAD

**Issue by pengjugame** [liangwei0101/egg-demo#2]
如果Schema中定义的类型关联么一个User
```
XXXSchema{
belong: {type: Schema.Types.ObjectId, ref: 'User', select: true},
}
```
那在这个结构中的Interface对应的类型应该是什么呢？
```
IXXXSchema{
belong:  ..???
}
```
谢谢

**Comment by liangwei0101** [comment]
假如user是一个单独的Schema

userId: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    }

**Comment by pengjugame** [comment]
> 假如user是一个单独的Schema
> 
> userId: {
> type: Schema.Types.ObjectId,
> ref: 'User',
> required: true,
> index: true,
> }

如果这么定义上面的Schema,那下面的Interface里的userId是不是我就定义成any类型就可以
```
IXXXInterface{
 user: any;
}
```
