### ISSUE TITLE
大佬可否增加 graphQL 的 订阅 和 上传文件功能？

### ISSUE THREAD

**Issue by WangShuXian6** [liangwei0101/egg-demo#7]
>大佬的项目非常优雅，我想用在一个项目上，但是很需要 文件上传功能，也需要订阅功能，请求大佬增加。

>目前在用分支：egg-ts-mongoose-graphql-websocket

**Comment by liangwei0101** [comment]
你好：
       文件上传，也是要一定要graphql吗？restful支持起来是最简单和最多例子的。订阅，我这边用的是websocket，是能起作用的。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: 王树贤 <notifications@github.com>
发送时间: Sunday, April 5, 2020 1:13:06 AM
收件人: liangwei0101/egg-demo <egg-demo@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [liangwei0101/egg-demo] 大佬可否增加 graphQL 的 订阅 和 上传文件功能？ (#7)


大佬的项目非常优雅，我想用在一个项目上，但是很需要 文件上传功能，也需要订阅功能，请求大佬增加。

―
