### ISSUE TITLE
因为警告信息，无法启动生产环境的服务端

### ISSUE THREAD

**Issue by WangShuXian6** [liangwei0101/egg-demo#8]
>因为警告信息，无法启动生产环境的服务端

>于是更新 typegoose 为 @typegoose/typegoose 后，因为新版typegoose去掉一些接口，程序出现很多报错

>相关分支：egg-ts-mongoose-graphql-websocket

**Comment by liangwei0101** [comment]
你好：因为警告信息，无法启动生产环境是因为什么？

因为警告信息，无法启动生产环境的服务端



发自 Outlook<http://aka.ms/weboutlook>

发件人: 王树贤 <notifications@github.com>
发送时间: 2020年4月5日 3:35
收件人: liangwei0101/egg-demo <egg-demo@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [liangwei0101/egg-demo] 因为警告信息，无法启动生产环境的服务端 (#8)


因为警告信息，无法启动生产环境的服务端

于是更新 typegoose 为 @typegoose/typegoose 后，因为新版typegoose去掉一些接口，程序出现很多报错

―

**Comment by WangShuXian6** [comment]
>旧版的 typegoose 不再维护，已经迁移到 @typegoose/typegoose，部分接口废弃和变更。

>因为我用了@typegoose/typegoose。暂时没这个问题了。

**Comment by liangwei0101** [comment]
你好。

       我这边其实是做了@typegoose/typegoose库的升级的。但是在别的分支，没有合并。一会合并一下，可以看下。希望可以帮助到你哦。谢谢。


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: 王树贤 <notifications@github.com>
发送时间: Monday, April 20, 2020 4:00:33 PM
收件人: liangwei0101/egg-demo <egg-demo@noreply.github.com>
抄送: liang <liangwei0101@outlook.com>; Comment <comment@noreply.github.com>
主题: Re: [liangwei0101/egg-demo] 因为警告信息，无法启动生产环境的服务端 (#8)


旧版的 typegoose 不再维护，已经迁移到 @typegoose/typegoose，部分接口废弃和变更。

因为我用了@typegoose/typegoose。暂时没这个问题了。

―
